version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9093:9093"

  redis:
    image: redis:7
    ports:
      - "6380:6379"

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
