spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${AUTH_MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}  # Jenkins에서 주입받음
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
server:
  port: ${AUTH_SEVER_PORT}
