spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: localhost
      port: 6380

jwt:
  secret: test-secret-key-test-secret-key-123456
  access-token-validity-ms: 900000      # 15분
  refresh-token-validity-ms: 1209600000 # 14일
