server:
  port: ${AUTH_SEVER_PORT}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP} # e.g. localhost:9093

    consumer:
      group-id: auth-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  # 또는 event.events, event.payload 등 명확히
        spring.json.use.type.headers: false  # 명시적으로 꺼둠
        spring.json.value.default.type: event.events.Event  # 항상 Event<T> 구조로 역직렬화

    listener:
      ack-mode: manual_immediate

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${AUTH_MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 또는 create, create-drop, none, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true



  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-ms: 900000      # 15분
  refresh-token-validity-ms: 1209600000 # 14일


oauth:
  google:
    client-id: your-client-id
    client-secret: your-client-secret
    redirect-uri: http://localhost:8080/code/google
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
