server:
  port: ${MESSAGE_SERVER_PORT}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP} # e.g. localhost:9093


  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MESSAGE_MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 또는 create, create-drop, none, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true



  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


app:
  kafka:
    event-topics: user-profile-created-topic, user-profile-updated-topic
    consumer-group: message-service-group
