server:
  port: ${MAIL_SEVER_PORT}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}  # 예: localhost:9093

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


logging:
  level:
    org.springframework.kafka: INFO
    bind.mail: DEBUG
app:
    kafka:
      event-topics: user-registered-topic,email-verification-topic,user-login-topic,user-withdrawal-topic
      consumer-group: mail-service-group

