server:
  port: ${IMAGE_SERVER_PORT}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}  # 예: localhost:9093

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${IMAGE_MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 또는 create, create-drop, none, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework.kafka: INFO
    bind.mail: DEBUG
app:
    kafka:
      event-topics: profile-updated-topic, profile-deleted-topic, article-created-topic, article-deleted-topic, article-updated-topic
      consumer-group: image-service-group

image:
  upload:
    dir: ${IMAGE_UPLOAD_DIR} # 이미지 업로드 디렉토리
