package event.constant;

public enum EventType {
    USER_REGISTERED,
    USER_WITHDRAWN,
    EMAIL_VERIFICATION,
    USER_PROFILE_NICKNAME_UPDATED,
    USER_PROFILE_CREATED,

    USER_PROFILE_IMAGE_UPDATE,

    USER_PROFILE_IMAGE_DELETE,


}
